const CONFIG_OPTIONS = 'CONFIG_OPTIONS';
const DEFAULT_TTL = 86400;
const GRAPHQL_ENDPOINT = '/graphql';
const MONGOOSE_CONNECTION = 'MONGOOSE_CONNECTION';
const TOKEN_KEY = 'x-jwt';

export {
  CONFIG_OPTIONS,
  DEFAULT_TTL,
  GRAPHQL_ENDPOINT,
  MONGOOSE_CONNECTION,
  TOKEN_KEY,
};
